### ISSUE TITLE
Conversion issue when evaluating some expressions

### ISSUE THREAD

**Issue by rohanag108** [Axiacore/py-expression-eval#17]
Consider the following expression:
```
Parser().parse("x/((x+y))").simplify({}).evaluate({'x':1, 'y':1}) 
# this gives 0 as integer instead of 0.5
```
The "workaround" seems to be 
```
Parser().parse("x*1/((x+y))").simplify({}).evaluate({'x':1, 'y':1})  
# this gives 0.5.
```
The evaluate function somewhere returns a integer 0 and drops the decimal place. Should there be an additional optional argument to return the result with desired precision?

**Comment by vero4karu** [comment]
Thank you for reporting this error!

Fixed in https://github.com/Axiacore/py-expression-eval/pull/18

**Comment by rohanag108** [comment]
Thanks for promptly fixing it!. Seems like change is not available in 0.3.3 version via pip?. Its still showing the same issue.

**Comment by vero4karu** [comment]
@rohanag108 It's not possible to update an existing version en pypi, but I'll include it in the next release.

**Comment by vero4karu** [comment]
Added to https://pypi.python.org/pypi/py_expression_eval/0.3.4
